- name: Demo on conditions
  hosts: localhost
  tasks:
    - name: print Linux
      ansible.builtin.debug:
        msg: Nabi, Linux
      when: os_name == "linux"

    - name: Print Unix
      ansible.builtin.debug:
        msg: test, Unix
      when: os_name == "unix"