- name: Demo on conditions
  hosts: localhost
  tasks:
    - name: print Linux
      ansible.builtin.debug:
        msg: Nabi, Linux
    - name: Print Unix
      ansible.builtin.debug:
        msg: test, Unix
