- name: demo on filters
  hosts: localhost
  tasks:
    - name: sample test on filters
      ansible.builtin.shell: uptime
      register: in


    - name: print how many members login
      ansible.builtin.debug:
        msg: "{{ in }}"




