- name: demo on loops
  hosts: localhost
  tasks:
    - name: loop
      ansible.builtin.debug:
        msg: Fruit - {{ item }}
      loop:
        - apple
        - banana
        - carrot

- name: demo on loops
  hosts: localhost
  vars:
    fruits:
      - apple
      - banana
      - carrot
  tasks:
    - name: loop
      ansible.builtin.debug:
        msg: Fruit - {{ item }}
      loop: "{{fruits}}"


